import { DailyData } from "./types";
import { aiNews, politicsNews, stockNews } from "./mockData";

/**
 * Try to load real data from /data.json (generated by fetch_and_summarize.py).
 * Falls back to the built-in mock data if the file doesn't exist yet.
 */
export async function loadNews(): Promise<DailyData> {
    try {
        const res = await fetch("/data.json", { cache: "no-store" });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data: DailyData = await res.json();

        // Basic validation: make sure each category has at least 1 item
        if (
            data.aiNews?.length > 0 &&
            data.politicsNews?.length > 0 &&
            data.stockNews?.length > 0
        ) {
            return data;
        }
        throw new Error("data.json has empty categories");
    } catch {
        // Fallback to built-in mock data
        return {
            generatedAt: new Date().toISOString(),
            aiNews,
            politicsNews,
            stockNews,
        };
    }
}
